#!/bin/sh
#
# pal - paleta wrapper to be comfy

# palette directory (hint: change this!)
PALETTES="/etc/paleta/palettes/"

CACHE_DIR="${HOME}/.cache"
CURRENT="$CACHE_DIR/current-palette"

rand() {
    LC_ALL=C tr -dc 1-9 < /dev/urandom |
        dd ibs=1 obs=1 count=5 2>/dev/null
}

[ "$1" ] || {
    printf "use: pal -h\n"
    exit 1
}

if [ "$1" = "-l" ]; then
    ls "$PALETTES"
elif [ "$1" = "-s" ]; then
    if [ -f "$PALETTES$2" ]; then
        mkdir -p "$CACHE_DIR"
        paleta < "$PALETTES$2" > "$CURRENT"
        printf "Using palette: $2\n\n"
        for i in 0 1 2 3 4 5 6 7; do
            printf '\033[4%sm  \033[m' "$i"
        done

        printf "\n"

        for i in 0 1 2 3 4 5 6 7; do
            printf '\033[10%sm  \033[m' "$i"
        done

        printf "\n"
    else
        printf "error: palette does not exist\n"
        exit 1
    fi
elif [ "$1" = "-r" ]; then
    set -- "$PALETTES"*
    [ -f "$1" ] || {
        printf "no palettes found in dir\n"
        exit 1
    }

    shift "$(($(rand) % $#))"

    # call ourselves again if we found nothing
    [ -f "$1" ] || {
        exec "$0" -r
    }

    PALNAME="${1##*/}"
    mkdir -p "$CACHE_DIR"
    paleta < "$1" > "$CURRENT"
    printf "Using palette: $PALNAME\n\n"
    
    for i in 0 1 2 3 4 5 6 7; do
        printf '\033[4%sm  \033[m' "$i"
    done

    printf "\n"

    for i in 0 1 2 3 4 5 6 7; do
        printf '\033[10%sm  \033[m' "$i"
    done

    printf "\n"
elif [ "$1" = "-h" ]; then
    printf "usage: pal [-s palette|-l|-r]\n\n"
    printf "-s palette  Select a palette\n"
    printf "-l          List all palettes\n"
    printf "-r          Select a random palette\n"
    printf "-h          Show this information\n"
fi
