#!/bin/sh

SCR="/home/diego/imagenes/capturas/screenshot-$(date +%Y%m%d-%H%M%S).png"
SCU="/home/diego/imagenes/capturas/current.png"

full() {
	grim -t png - | tee $SCR | wl-copy -t image/png
	cp $SCR $SCU
}

geometry() {
	grim -g "$(slurp)" -t png - | tee $SCR | wl-copy -t image/png
	cp $SCR $SCU
}

main() {
	if [ "$1" == full ]; then
		full
	elif [ "$1" == geometry ]; then
		geometry
	else
		printf "use: scr <full|geometry>\n"
	fi
}

main "$1"
