#!/bin/sh

if [ "$1" = "up" ]; then
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
elif [ "$1" = "down" ]; then
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
elif [ "$1" = "toggle" ]; then
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
else
        printf "use: vol <up|down|toggle>\n"
fi
